apiVersion: 1

datasources:
  # 1. Conexión a las métricas del sistema
  - name: Prometheus
    type: prometheus
    uid: Prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  # 2. Conexión a los datos de negocio (Para tu tabla de transacciones)
  - name: PostgreSQL
    type: postgres
    uid: PostgreSQL
    url: postgres:5432
    # Asegúrate de que estos datos coincidan con las variables de tu archivo .env
    user: app_user 
    secureJsonData:
      password: app_password
    jsonData:
      database: smartbancs
      sslmode: disable
      postgresVersion: 16